version: '3.7'

services:
  app:
    build:
      context: .
    ports:
     - 8765:8080

  nginx:
    image: nginx
    ports:
     - 5678:80
    volumes:
     - ./app.conf:/etc/nginx/conf.d/default.conf:ro
     - ./html:/usr/share/nginx/html
     - ./install.sh:/usr/share/nginx/html/install.sh:ro
     - ./builds:/usr/share/nginx/html/builds:ro
