apiVersion: v1
kind: ServiceAccount
metadata:
  name: servo-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opsani-servo-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
# Enable all permissions in the opsani namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opsani-servo-role-binding_opsani
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opsani-servo-cluster-role
subjects:
- kind: ServiceAccount
  name: servo-service-account
  namespace: default
---
# Enable all permissions in the default namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opsani-servo-role-binding_default
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opsani-servo-cluster-role
subjects:
- kind: ServiceAccount
  name: servo-service-account
  namespace: default
