apiVersion: v1
kind: ServiceAccount
metadata:
  name: opsani-servo
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opsani-servo
rules:
- apiGroups: ["apps", ""]
  resources: ["deployments", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opsani-servo
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opsani-servo
subjects:
- kind: ServiceAccount
  name: opsani-servo
  namespace: default
